{% set version = "1.8.0" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: 81e70ddfbc8f52a8925954b5f3dd136ad1473a65e0a36132cd94f9c3475d0c6e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - netcdf4
    - numpy >=1.14
    - pandas >=0.24,<0.25
    - pygc >=1.2.0
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - six
    - cftime

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
  commands:
    - pytest -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: 'A python framework for working with met-ocean data.'

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
